//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodfestdeneme.Models.Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gruplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gruplar()
        {
            this.Rezbilgi = new HashSet<Rezbilgi>();
        }
    
        public string Grupno { get; set; }
        public string Raftingtür { get; set; }
        public string Gno { get; set; }
    
        public virtual Görevli Görevli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezbilgi> Rezbilgi { get; set; }
    }
}
