//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodfestdeneme.Models.Veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Görevli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Görevli()
        {
            this.Gruplar = new HashSet<Gruplar>();
        }
    
        public string Gno { get; set; }
        public string Gad { get; set; }
        public string Gsoyad { get; set; }
        public string Gcinsiyet { get; set; }
        public string Gtelefon { get; set; }
        public string Gemail { get; set; }
        public string Gmaaş { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gruplar> Gruplar { get; set; }
    }
}
